#!/bin/python
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. If we list all the natural numbers below 10 that are multiples of 3 or 5,
we get 3, 5, 6 and 9.The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
"""
a = 2
b = 3
sum_febo = 0
for i in range(1000):
    if a>=4000000:
        break
    if a<b and a<4000000: #safety check not needed in practice
        c = a
        a = b
        b = c + b
        #print("c val ",c)
    if c%2==0:
        sum_febo = sum_febo + c
print(sum_febo)
